# Generated by Django 3.2.13 on 2022-04-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='motogramuser',
            managers=[
            ],
        ),
    ]
