# Generated by Django 3.2.13 on 2022-04-26 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20220426_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.motogramuser'),
            preserve_default=False,
        ),
    ]
