# Generated by Django 3.2.13 on 2022-04-27 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20220426_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.motogramuser'),
            preserve_default=False,
        ),
    ]
