# Generated by Django 3.2.13 on 2022-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vehiclephoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
