# Generated by Django 3.2.13 on 2022-04-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclephoto',
            name='photo',
        ),
    ]
