# Generated by Django 3.2.13 on 2022-04-29 13:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vehiclephoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
